### ISSUE TITLE
Light Theme

### ISSUE THREAD

**Issue by mike-ward** [porsager/flems.io#10]
Reason: Dark themes don't always show well on projection systems used for presentations.

**Comment by porsager** [comment]
That's a great Idea mike.. I think support for choosing the default codemirror theme should be good enough.. I'll put it in flems core first..

**Comment by porsager** [comment]
Added in https://github.com/porsager/flems/commit/88506b9e101f252b1db0447298762471b6bf3c36

Use `theme: 'default`
