### ISSUE TITLE
Where's the source code?

### ISSUE THREAD

**Issue by styfle** [porsager/flems.io#11]
Is the source code available?
I found a link to this repo from https://flems.io and expected to find the source code here.

**Comment by styfle** [comment]
I see now 👍 

Maybe you should add a link in the README of this repo.

Or better yet, create a GitHub Org to house both repos.

**Comment by porsager** [comment]
Yeah, that'd probably be a good idea 🙂 

There's a link at the bottom of the readme currently, but the readme here in general could need some improvement.

I mainly created this repo for tracking issues, so I honestly haven't given much thought to it.
