### ISSUE TITLE
external script tabs always open externally after adding (until reload)

### ISSUE THREAD

**Issue by fuzetsu** [porsager/flems.io#13]
Steps:

1. visit `flems.io`
2. from sidebar add dependency `mithril`
3. click mithril tab (expected: shows content, actual: opens externally)
4. refresh page
5. click mithril tab (works as exptected)

_Tested on Chrome 67.0.3396.99_

**Comment by porsager** [comment]
Thanks @fuzetsu ... Finally got around to fixing that too ;)
