### ISSUE TITLE
changes to css aren't persisted automatically

### ISSUE THREAD

**Issue by fuzetsu** [porsager/flems.io#18]
If you type some css and then refresh the page before doing anything else the css will disappear. Guessing 
this has to do with the css not triggering a refresh of the iframe since it is injected (?).

![2019-03-07_16-57-41](https://user-images.githubusercontent.com/848652/53992339-91956700-40fa-11e9-8ba0-59ed5af6e292.gif)

**Comment by porsager** [comment]
Oh, nice catch :) Thanks! That's fixed now ;)
