### ISSUE TITLE
support editing external esm dependencies

### ISSUE THREAD

**Issue by fuzetsu** [porsager/flems.io#20]
The feature that lets you edit/patch external dependencies is awesome 👍 

Unfortunately it does not really work for esm deps. Importing an esm dep from the sidebar results in the error: `Unexpected token export`

Importing from inside one of the JS files works fine of course (`import b from 'bss'`), but there's no way to edit this dep.

Maybe it's not super feasible, or worthwhile to implement, but I've found myself wanting it a few times so I figured I'd file an issue.

**Comment by porsager** [comment]
Ah yeah, this is slightly related. https://github.com/porsager/flems/issues/62

Let's continue the discussion there as most of this is in flems core ;)

**Comment by porsager** [comment]
Oh sorry.. Not nearly related enough :D reopening
