### ISSUE TITLE
Large file lists result in a very weird layout bug when you attempt to hover

### ISSUE THREAD

**Issue by isiahmeadows** [porsager/flems.io#22]
Steps to reproduce:

1. Go to [this flems](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcICyBDAlgOwDoArMEAGhFgHs8wqY1L6osAHSFCgMxxlNQDaoPFgC2ERgQAW8UVHJM8iJYwA8UiFiQA+ADp59AAmOHV4+FkOwpWAE6R4AXl0gArvC4BaABwu9eE1NzSxFxZxAANxwIAHdWKlt4FysaZScXGJwkeClHJAgo2AhPTOypMkN8HHgcLChPMFg6iEcARgIABgrRLAAPHFFXUQammDaK10hbEbqsACMxvCo-IxMzCAtDGXhWTwgAR1ccCPCADU8AVQBBTwBhKlFWLBqFiGTqJQglcOtbB5bWisAmtgoZQi0XKIqHNeMUYhA5p42Lsmk9Xu9Ul90iAAJ4QMBAwLrTbg8LImCeKEwinwxHIzyo+YwDGfb4uPEEkD+VbGVQ1eAwbQAZQASiLVAB6fmCnmmKD4ADWhls0HCYHgOL4Gg2yQ1rAhIEQvXgEtgYE5WxVXDVGpgBDNnP8RPleCVKqgNs1+O1SRAlog1pc23YqAlpqQeBI9qgVFcSC4LBV9oeEqwRD6EvlczAqbwA2eEHt5olAGYCAB2Tq5-OIAiifBFx2y1Qut2qlzqr1gH3JKRW8LBsCh8ORsDR2PxxOF6iiVPp3qZnDZiVcB5YJQ4WCeI4SgBMFYIu4lkB6G9gdYbDpcssCxnwiAA5rZqji1TZdwBWABsJQA4gBRUQrm8PAAHkLlsAARbwAClbAAFgAL1-CBvHxWwFQARRiWAYKIK4FSgAB1ABOAA5XcMAgBVTglCAMHg8IrD+c0EhwB98DJJY8BxKFJhcCVuTwSUNC0fxVEaZ9WHgQwwFsWAB3gHYhzDVw8FYBUH2TWd6xyZ8oAAATwCBjQlXS+14YhHUlSScGk8TbOk2T5MU5Th3XAYICjGdFzmatxAvQgSD8GzYCk+AHLCuyZLkhTeyUkNVPUzTtIlJAHk8GNYAVHEQuPKL7IUSAYAQHAaH4EBWnLVAP13TxWg-VAOhAABfMhhDECR0AuKYMCofIoCshQPjSRhDAiOxDB6iBbEMRxDGAWV5XVVBDAEABdMglqoLQABkcBWwwuDU0qaAACgASgWm8TBVeBXFsAJRAIFVDnxeAzsW4Fb1vcwpH61aXAAgAVFwtu+n6TAeqBAZAQdhxVYYVXVJFWBwaQZqoBVXGRVK2BwCVJhmzlwch29MhyW4VXyDc6iHQx4FsVwIFJyGWoum7jAIHIvjO468FOvAzuR1woHgK6vrJwJptsAhlpk+aRbFggkGeLBOcMdnZTa-RZVgB6VSUVbgB1iGYy0Vb+cFs6sgljW7oep6XoOZn1U+jXAj+gHDCB-9QfID2odsGGfbhhKVIlRHPGR+BUfRjQ-mx3GfPxwmphzZIAGpKiQVmpcMCmpCp5AsVqKB6cZ5m89vLWIcCbmNCFq2anOpXxeuuvIZl+0DaxOblXxUWkk74xa8CU3ZTALAIggS2TpboW7ZHgf7sewxnte12Psl-P142f6kFhgAFC5-ersnodh+GwyjmO44xxOcdYVg8bRtPiYlLOpqmHvbEN+ACBZHPpDVWFhVrd31n-LEwCfqF2LjTGodNVqVxZhrMeJgWr6BakVaAcAF4VVaB0VAhDWrtRAOCRgR8sAPggMDWw64wDVDKkFUgFARpYkYM3ZhhhTi8LAPKfIABJMC7gzpIBwCqQWFQ-juAgEKCwiAKg0HuI8GAiAF5L0CDfWMiB5EFm5vQ2gTCaB6NrPgOhDDjEBHmig3WZsNgMxLEgPRiR+7iMkQvOajh5oAHJVy2BiHYJAPjDAAH5DA+MZgwlgiAnFnXqh0DoABSCoXRDAdAuiE1akTDH8ILHEwhyTUmpMyUtBx8AnH-jwEgNxEi8HcO8b4-xgTbDBLCREqJtAYkQAKYklJ6SSlZI6bk7pcSElFIGek0pBh7EyXwHMWM1SwD91AnMIgeCCATSgK7YWOi5EKMLDQ+AwiFlqSQJdQBiBRBgA5jMwI8zFlIDHP4-8WBrBnRtvACoOArqOG0B3Mm1RNlLHyCrB4BBOx2k6WAfxoh+4VOcRYRIGsgUeR6J4+aQKIggsLOlZ6aKCxnQEIHYwwBoWwuQU4lx8BTa7wWuShIohsnQtGectJ7LMmYOXptBaSAHrPGYatEsiTa4ooAQSheBAaA8DzN2ful05r-J3vnMMHw6B2hjA+M6PiHlnMMBK7hMqDpIA0ME25dKsU4rBc9SFhYGW2Dhb4nxdi6VhkMKBAILB1SVCuZUT1B0vkDwcAzDQkBZIHMMKwP47ACAksqFwQwNsvGYrwKcpZcsvgPhyIYTwhhWiaLpbdPZpjCzmNyVY-uXA6ZvGXmTN1MjdEHO0qwNRdrG4fK4L8-5XBLrmsLcYbRsiS0GMsQvYd6ULFGIxUdatcauVk3nRg25ZSZI6LTU8lZayNlbJ2Q2-Z+ijmgXcOui51QIDXL7cYNdjznkJFee8z5XaO5ioIAamg-dLX9VxeCiVEAiVxrJbkilwzon5LZcUqZPjaW70Aww4DCKqlIEXT9HlwA+X0IXkKkVl7byorzOi5hUq8BGrlfNBVfyAW7zVfQQsmrtXXr1W+gIJGTXIB8ThwFACo0PAOoWZG9AZ6XTQdrZdENdXppeW8qQHzqhPrwzWQjLasA4jOsKjJOGGMSbvVJmT7cKPyYIzQAgSmVNqYurcrl+guHvqrUIkRH090lqUQLB4LaNjMILcYNRhhNMbvmqs9ZCBNl1F3cWpth7j2PNPVcm5dY2CfMVT64FX7rU4e8+Jvz7qt1BZ3fiXZQ7wsbBOVFi6lzz2xZ6KwBL+mAHYpS3i0TgRqMaqoFqlwVwyKCIwP+MGPnItnLAN81NN7GsmDRX+5Vt4kVHPphlwbGsqBPFgC+VaAg0mtE2hrdDAqaBYa6BrTQjC8APmyS6TQthnUQ3QcYcb7tl7TY2PTXz83l6LbeStgZW3+WYcMGpmBhhDv4BOxEs7dgfH-ZnG5xAq0aCQ7UcwkTWC7HWYCPwrIEAj3wF2gGeAQoBEQGESKdiMh8uNoLM5uH7maCecMN557m7Au1ZC3lxzhX4CY5PaVs9F64tVeqIlz9oKGsrr9eu5Z-nstM+2SzsLB6ivDbOdF8rpXKvVf+YL79ohRs3fwxNjWD34CzYV0s-7LKCynFWz4wpSTwfpM28vbbP3dyJP+4D47p38Dncu+PHDt3JuBAN09-rJv9cjPN5b8ZNv7dk0d4Kwwzv9vLzd8DnxoOLsQ9c62mHLnVFU7uUupHMyUeyXx5jonD4ZB4-R8I7HXAHOy8UT5nPUOPOUa8w4+nEvGfBel2AUn+7awRfgJzsrPPVf85q8loXDw0sOLmwz7dzO++s7l8c435yucxZV-Fif6vatWuF-nnXnk7tk0D6tObpuw+IAt2tHxkfbcdGjyA77ceE+u6wEdlPafvcF4hn7-XOwGbGHYPJ5K-UDG-S3a3HxZ-H6WPXbePF3A7T-IHD3YyMHDPXPaHJvSnBeRHPASzPAHBEqfBRgQheCJqUhDqcQRgKiPAVwIaNhTEFQdAMMfQN1MiKgHIIHBmKgWSCACALYGaFmH1HxZZIgSYGSSwJTfAHzKAGpcyfSFIR4GgLEdgz+YjeebhOg1wBVL6EXAAfRX0QH7jOQDE91zg1gMJECiAfGeASFMOqXMOMiQBdVug2Edjb1vCiFiFWk+meEZnpmAGMJEJsPYnsNsBanZkS390hiMIb0EMVgSLjWsOnnCPgAcPmjCLsIyNsDcPzma1o1a21R0NQFQB8JiFt2CISNWhCIqGyIiNWgaNyNFVrXcNXiem1RsIICOG5kW1fSUik2QDrC+FcCqNgC9XphCMAXX2TQiQlBCXCR1TwBnkSGQEMAWGZiGR8SgwqGJTaJ+lEG1TlkVFHyqLjTJlh3lGyiaOnm1QWI413jagiQAAl-h2N-syYjifETjXQziKhYj+0rjNwFRbiIh7j9Z1R-h7AJREJEJ2MLiMEKgfFbhJDoSwAPjETjBvjfiFR-ivD+0r0BZrjQSwQ7ifF357AESDia5kSZYMTHiUNGTNZ8iWSj8jotD30bD+8adAgHY14zoIAn1ATbxUjbCIiCBjJjRBTpE9lmTkM2TC9iD6lypGASxqpmo2pqCuoQAWAcQdFGDFBRpWCNCOCuCpAeCMj+DBCE4RCJDvU6BxBw0BVYBadlMdErBzRPB8BPAox1D9AJpZo9SdFxcvDgz3BWhjYNZkQoyaTxEwATNsknwshwc40NBid4BslCkIgpBUyaTSgcgszEkIhKjPiTAqBViEwqAYhskLSkAaY8y6U7DWBskSxWBehft2zGzd4fFkykBPArklNEAGR6AhhaAfEsyuBZpWgpy80pzuz85eznx+zBzulo5qyMTsl6w8ARzWQpD3A+Dtzdy0hf8fpoMfpRJ8hbBYy6UlysgRztlRA8AJyIlWhDAJRDB4IFypY7z+y-hKisz3y81TzaTozGF8gbyey+yHyxyXyrcgKvyyzjAfEehegSgsgcg4LdwvwOguykKGYgNGVmVr8IBTh4lrdMl8LoUrFiK4NGVftElrlvyyZfz1yALXyELmLIYfFEJvSnDegXySJ8L4zEyIkEwTIuKfo-EYA0L3EVTnzslqBHznz8KfEKyZoqyYhPAcQ4KsADzJLbx79aQFRqhPB1LbBNKRg-goAXQHw4KMjXBrAQLx5-seh8BILFzoKlLYLAKPzEK41WL-ysKgLdwDLAgRK9TslxKBLVLorPA5LBY4LvKnywqTA1LKyYwtKdLaysgGz8L0yK9MyIk9KMjUqB0PyjKEQTLY5zLLLJJmAgd7LYwnK0F-tVwuCZoPKfyvLRyUrfLPyyqIloKgrWygKSxnKMFtZq5oqurAgYyCSQEDpRLpKJLYqZKSh6FWA4KYhNrBqVrZK6lErFLeqVKAqjyCqZA4LszczVKjyCzcyiyOgSzBrarMqcr6yvgJrR5-tLzOqFqLyIAMzHquzWqNY3K8BZrIYZrXyvrNY2qqAOrrz-rbwLqiqrdEkQbl4FSuUuVlTBYKovwKDNSyEKF0BsAGwSBhpmD4BGABh4hXFgAyI0iciEgWojo-g4UfiJQmbxTJUSBLt9A1UZJ9pvUyNhSRdio8FkBBEal5ozCZVkBZR+SAgRSKi-DgAAj7AKhrBeAkBDZoiKMRS+SPC14cTej6x6y7Q6h2IXCIVcFBZnYWBehhjEwaETj1RziaTAhbVslXrqztLUASqqBYaXKrALT5DDZ5TtZWTi8DDgTsobYkBeSTB8g5hXAHwaE8jl5JaEBpbZac5o6CC7EhbDARbjlfUxaYjDCshHD8gFbXCIZlbkaaAqgir-ClJ7BjYsgoin0DCa7MVLDl41bE0NaO7Bsw7db9bxaaSm6cTudPbCScCSS-ChTEtNaxxmiEhJSTIPoRCBJISMjxBbBP4-Rs4+7c4S90dMda9cd8dCcMzmTQ79jF6cTnxCqCAqyCwkBkw9zbdvj0Zei36ZA5YgDCxNjCx1wHw7RNwaB2MLp8LPZjj2ElA-7jjfr08J6I6vhzN8L1ptca5C7CDvM91Qzn6TARSnhCz5iDKPgeBgcjaTBwyiqmGxwmHWh8LucgisT3zUxwLZ5E0Qin1viqiQjaiEiKgfaUK+h0KygmouznifEUD8gb7MSvaTB0G-C6iyTeaEghGzodCATRHlRxHtH0iEgwSzHIj4HuGwwlH+H+8S09GdiASfaIlUbiE+kABuOYN5TSGRapB88xvEGy6s3Y4qvh1Rl+3ACGgRhIpxqo1xnxdx63bx3xp8R5QJ68uYQGmhMJpJ946xtR4wdqxAJG8jf5M29GVYmoUYO2h8cQFB5EkpmaSJp4-C+WL4YmSG-OFu9fTRuJquop28QouWYoikpvDLW3QR7h88wtGgXzfpgrAsaexeprcqGjUZrVcZ+Z0AqZuJmZhB8skQOvGaamehGs2JpZxAFZ1Z4wEZujbZ450ps5rAUs4xq5oUmZudYTdk54ih54KQbJU0NEo+nMVAdqmh6VdiPw4vPQuNbzAw+qmy4GRbWu5wxWmek2lW7hph1aFhkB-UiMw5u8GLbpwtDRy5snRvTe2wPRgxhaIxrRmlixlmqx4l36aJvwp9Mh25xB5x5G3l8NL0bJHx7KdJs5TJ1aJ4GAJ8AQ587hhdZEoUMKZgFIPc6RLF-VapWSFV5F1Fg6fggBVpwV7Es6MugE5l0x1l2Zk1kwN1K4MWGaEQGoGeHESNT-ZZJFqAFF1gfVZZTW2NIZulK4P+ZTM6HC0rHgGys6DJXnD5Aw75PRsuwRK5AErIC-eo5mxoq1iIhRg+6EiJQwbOH5R+wk0t-OWA1ZsMZpsppxmt23RRpYHmWaet8t0CoZjp4yTugV3eXp9dRZql1ew2hVyGe5sZ4FqE0FiZ9fBt4NL13gra2Uj5ioRF3V71xbNtxVkdokhZylgfIdpVbd4Z9ZlrLZidw+4mJvXzBtp8eYHV6yqABdvZj5zd3ebzYATh42cGqI-uaYofTnI9wIVdh9n1-ucGqfTXAgN6WwHEIUe23I443o+WdjCFNdn1uxI9m1wkmgLAE5qBPW15gd-dm521sds9-NqdnDvDl5t56ZoNyGd9yh8oH1crL96Jn9pIj5ggI5YrRXV9-OHABNM6JjuY-ekFj+cFhG5IAAMmk8MGA+YB9augcGBk8h0Q+RI9tchjdWaESDOgU71dYH49WfA7q2n2emg9g-g4SEQ-RmQ9Ky9dA-mgM-XdYEA7ZnZbpTM0w6+ZpIVJ9yE1+YBI1iY6BaJipIz2I2hZ7a83dPcDxbi8NwJZ0XYbjU-Zi5Rs0CvKI6cxzdyLpdGMMZqPecHczZ0aRppfZnZYlAACp3P84KWHGDkyvLH4mXHbR+GkmcmZBVp4Jdx5HuhbOCA06lJYHgv6Pbn47STBSn0aXhvfGZTL78gy8Myq87Mb7jPF6FGAAhXxuB9lmrjQqJ9yvdxxwZwVpunlk14R8brT28Xp6oLl87u70dk9oos98LocVAB7+Aakl7pE+r28RJ0VvxjJpS8x91mVlUT6wHhRnm3QXQZYh8IQlUAi9iTO-19eL9R982b+4167s6FwHoqYTKANXrbueWONs6cLzTu72e7VW3cLj+iRdUJmp07OEJEJbOJnr1eANnz5ibmuczI99aA57hmtp7ijYRttrDn6TtrpjLwIPtx5HLg5Wnwksj+46d9dZ9wdzbkwFTtT0RCnnaJAc1hijJMXoZqj555Ac51X5Z5725zXikz7pvXD23gj2j-ZoZ-ztmH50O-5qhikijmaCUVAFMyLuhslwIXFt0wlpLthjh0l59IZxrplrN-LxLG7haRJ9xz8-rgS54yp4b9wDIlSxXyGKble2bzPrekHxbtHZb9wcvSvO+vADbg5iJXb7Kfb1kulcGh365p31Zy7wHo4oMQEcgDpC05ZA10P2aLn9eF6PZYzOwMQU9JOkXq3xeiXxNeJmX9pgNTp7thhn6ZXs5Ifg9yvn6F3j8i-6pXX4jo9w38QdTk3vaANCobz339lm305u3oR1O5q8R+i9O-m73-74dzmT-Rxr5zpR+9R4hdUXjMm8w0t+4PNSxv3huR2IN4XwK8mIioD6wGmACBZEgBxB7FZQOJJoDPFPDmgngqMLaoUz5b2hp456BhAmSwCUh+odMakng3UIbw9kBAogViCg7MwYOcHEgjZx+LUC2BtADgQwI+LUMKgIoPZMvlUHC8Zkc3dUHYA+jSDWBtA+QciAbYPF9AeNUgugGqjwRia2pRgBgJyKEZKaTBPcrTRUIM0VBsiMAGzSnIPAIkBAbmrEBLTHQoAu0RLlZAFp4AQ29CHEMZj+AZE9QhYfUNRErSckAgZ0EHv3HzReFBOiabgqw0zTZp-kGSZGk3VyECBchGaY7NmlzQg91onjQusbQ6KGB5aFhOoQQVaH6ATI9NGSCXTsERF5UJDaeiLmaLMIS0-cEUtoJuJrRK24VQ6j9maEuFwCU6OPPMOQD-ZkQdCdHsISQA81VoKwhuuPFZIl066elMWJOkYTTp9OFOTPHnkGHLwXe0xaimOibSPDmEl0GASALDAVAmMEjEQKwCFD-QPoNhDQeoSb4Y53AN9NbgTjwCt968y7HAtcI0RxpbMUIzHE13JzwisCHmfQMrX74mBshZ0YYSYibQJUMU3iMSgkBaRmoMuoI6+jjkhH31CqaIxvLDgRFYisaAOcuIIXxGEi8A46WYQ0jJE+IQe7GakaXhb6rd2+N9JkSIRZGYjqcAfSauyRLpOl5o4wpFG3WRASC8ECQCRuqPcHD9h2NJAQbIiEFDARBlnLUQgBs6ajrOtLXUToP1EiE90IofEAJmJjylwYW2KgGcJor79QBr3WgBswea9DciZRCdOWgXhvCASLwhAjyOHQxiCCbbJurBiWGxjM+Iw54RGOYQIC4auIu5jADsA+ifs5TDLi7xDHmNUAExc7EWNeGUV6UWYtMbzQzH6IEx12KWHGMzGjoGkTQpwvXVBrslAgUpNuk6L2QVAEx09EZlWLsCBc6UfGQATEErSzoBxAY9VIWBaRCwfE5Y68qgCHFRiSuAvOlB2JbENjrEBFLse+gAA+F4wwMcKHg1iaAeY36Cv1kR21YR1zfsRrBB4r0xxJ49Xj9DnFe9FxnIx8Ws0DGnttUW4sog30yRtsjxtYBMfChPGGArxN4gMCcPgD3iZkaZANAkGiHQSPxy8eXqfxAlHMMsfhIAuPU3jvRkAVCHIH+Klhli6+24h-sEiXalc8uzY98cuPzjpZZinHQdtx3lyc5Whi9VAdPD0TZR+4cEwsBMIVAkSfo3I8SRYGygVCs0UgQwP8jfKydtGEkvEokIVBnRdwpWKieqBokAs5iJkxAEgFolSBk6-aaSSrH5HvpfEwoo9jYV0nGZFsM4wkmzWgBhoz+7Y9MUSP0QkjuxfiCkUEhDq7x3JykvSZMGkwBS6UFE1aBRM86QxLJZkqhhlOskAs0pP0PdDZIvzr41+OQPKVNhPEssdsvIzsamO4mFo2x8AudJ6JpI7Nh8KvP0YaLAFvdNmEEpiWUVak682Jz-Pzj80Loi5qisiF0eqlWKUSEibNeaI6LUEeDugAvJWpq3EDtCi6RBCgDnXMEgB4IJESglqXISdRbBAQg5EEJCEJ9DSyDGmugGIYJEZaGQjob0C6FqtvUi0+VPEWWnycaWtw2Pg4j3RPT5ogIJUeVBkghExhKKQ+PuJLQy1M4mcZqWTGRD-gQ4ew-7JazFKWMkZkMHjn0x7F10LC-2f9u1PRmPjfMU0t0VcGqRTSNguw3sRYTGmzJ9xlMqADNP7jfTEAY4amI5T-RnQ3kRA0WBEW+TwBMhnU7Th+QFlDAhZuRSoMsh5iGAMA1QCyI+z3RBo3R9gENM8EMBHIxCK8R2OsXXD7CJZTQjgLwXdbmhzZxoxAN5J+hSzBgMSBIAIGqDtAmO60fuEw1ZmrFPk7DWGc11+lMT8GWiD8i8WEIFwIAqeR9lCVR4Ky1ZtDdiK-nfSgJLAshSwJDOhCM4NYbqHINrKaABBsmA8LgMIQFjrFZCNAdFO8iuhGyB4ThWwBcntgJFnZoskqVIHdmqi40e6AANIQAcQYjWRPDMRlxpQuPqV2blPhaJcL8zc+OVpCYZH9TJXbWbFPKhYzzj+C85CdeJNijTl4bqAAGIOFNA1gFjqIAkYeFfWGcvBObODRmdBCVoAkNvI-JhRNAVk8aLUEMCBDRYV0j0pAGthXRRg5cQNmTBCJNzR5OQdaKPlDIBYNkCoHuX3hdk-06G4Ctts7D5RFAPk9smWQkF9nVAjJ-o-OOgsdm2BWgTc3cG3IWg5jAFmrfBREVBnwCASrRChY0KoW5EpqZC-BvcKxY8ESG2SIaV7PdGslkxzo10WzIV6CLppxMIaSWj7mDscayOFIfqmfhQBYOHXQUlAF1FegAsNOSBUFmgU4g+8tqDRR-W0wPpZMiWaABCg65NzSF+itZJYoszF1wZkaDmrxkwjMxmY-cDaHYjdTAxZ+zEJ+fiH1SGBHRvCltg4UsAcQZ4AQPdIG2LyeyhF3svdBIv9l-SwyDiAwtPN-ar9p5-2AqeZP4kJCx5y8KNAUBslos+x7JZMeTLwAVzAWiaVKQPDeimScpdEwZvC1SXlzngh8yuoaO4ZFKIgJSvJcOjxnrp2kf7ISSVhbmGB6ZhMlwvJOPZgS1xdgDce0vgDWBuFN-W8MlP1S2AHwL2C7i7GolNKal2UmyWVJyVZS9kJyo9r0sKmOLilALGZkHN3ijL2coBeVE+muXmTwkQCj5aAsmUEz0Wxs-tM8t47asul-yIBWctbncNpiFMuJRAGplIBaZCseTrCrEUIqkVsygGauleUDK2cHOErDiznx8S-Zq+EFRvkxUmARm64+jFUo6U1Kqiu7XzENn7ai5Hk9CjXt1IebLLD52TfxIISIkYlElyzClXeCE4ABCaYijKgBLwj2bqVumXD9QRBCBVUo9pKufioy3EhAs0UoFEEzQrOkguuXoJoHsD6BRg-XjdgUVKKvQ0o19OqtUWsqzkyXdwLaqM4iq5lq4nqWpVpUrL1J1gOACZXdwRJkSLE2nAGi7bvDhVgvDLO7WUDEwiMGWQwNpOjUCr416+aUY8v7SKTyuMak-mOBYlXQ5uKalifzO2WUT9ljSmyRmqli+TOR8aRNL5mfGIBu5brMVWSOjVdye5MqwXi725W+qNA2UVAkGoiS+ZQ188lpkKq4mCsG1RapYK8u0nTrV5cagaVFjo6Cse13qw+X6oHWBqG2IaoiRGsnW8tk1i6+wKmuGVJripM6jLOmrdX3IhOhak9XmtnVtSzkBapiTmoXlEZfMJanZRqwaVWTK1R7LNZYw-VLq8w6+N9dmqvVpq6lxygFlWoXRur111S-VHh1HWxqIuJKw9fnEIJ0pvMvrLIrEEMBHwnFkAD5PxmEUatGc9EsmOwrEVyy1lFGmeBOpELcZ6wkAFxRAGZjGd8REqhIjMUwl2TC0cdDddJnNXqzhFts+qRyP8lXLSNEATjczB6K0ALSdeT6Exv4YabnM1S1aCJuqUNSOV8yggKcykGQRQIb80CN1mBgvFBEZEf8GKoc2242Nzi1xQeJ8lzoENlKzlcURcC+sDosMCoK6sxaNC3OdUieMvENjZdE018mje0U8JHF35wQxLrd0JLpc0ly88Beyzj7paouM85LdCuK51FuGlrGlh5oVGID2SsdVFVTJpn4gNgcLOqT2tAK8L0VdW37oFvk2KbVphEjvDiqw2HINg+KvjhrC0VS4dkDazhpGyMXSZH0AuLjPJudhiLe0j46YmWnPGniq0wEh3FquIHDd+o0QiYh6zLrOwoQgmZYgORPHUkNYqAnev3Gc0cbXNnkqrMyW5E70hNwc1OunUzpxoqViywniABFAXAyInWMiL+HZo+D7tCm1wMzF6xDjYJ76qcbYEwlSayYQ4ojNUpR2Qw0dGmzHaPBk2CEApYYObojuR1tsSNPGSAItrdEXIeYQsEsT8vUly0GZLhKOr8zsSEFi8iWz+aIi7UNDPC+hV7PQVYCgJ7Go9QIsbAz7lce6LSmki7y50TzvuQukXQetLR4BBNsyunH1ueVDbqkl0CoGGAbV7p7guW9lgmtxWkq01V0MMO2r2TG66GsyuXRdI-kK6aArgYXQWFtwZYlEoBTzeVUMCCIE0SwPrC+uqQiy9Z8quoPuLS7irfM72lcRs2pViETKz8IHPUT4LXtjOOIkaXVODn+6E0U8J0gkrBDmlLSfBdKAAt3j4jDdeyZtXMRt2yJm1V0LPbMvxGra1dSExpARW43rLftj0bVGAGT1oxjsQ2M8bVL+6Eks9jUnPUWi45rbapiEmHXGR20iDSBB2yYsdq0DnJztCYq7TSXJ3sa5xS20rLTo04y7F6XinxQa3wBKroFNSD3jNBDSCFIE-8AeIBKoAJo05eyMOpAyf0Ij8QFe-tG6gD3hytgrA0fecOYTyyy9VAL4TJFyGRoqA94CoIS0jmgGZ4Gxc0jYw-IKyR11chNXimL35BlkJkANDwVkIKy8UABwtG6hFBqRH9qExhNTHANWJx61cv+fQZHU0BeVCQYQqdsEKQ7lkMQRuMoShyFgkN3mrZvLoT79SldBYRxRTqdHziRDraBtkzACAJiGSbq4DayzBSk6R0tUuPTxIcQpiIDNAeaXly3rhj1tuOwtAmOlEVASxiUp5fxrn2mGNtS4u7uuuUMbAIADmsVbblj2A8YVzWuFa1ocA2H4BvumuPjvWV8kXD7e9bUBMgCqr+N1W4RWEfq1RGDh0+2-hIe1RSGdEMht3SLvkMH6NWgE3AhHORJqGm8KG+-VANebobc1u+xeserHWnrIBNHRNXJzaMYan19Rmjjeut5zq5OC69o-0eo5KH51oBUDR0aeYACveQxsrWFpxk-Rh67dcXQyxMY0sRZ5WCoEw2l3dLZdeRnxAUfi7lFoglRKI7xOGXm7B8Yy4bTkdpwOIYAlQxnVlm7w6LYFW+VSTkA7matRtBAL458mVxU9qgibXBVLG8w6KP0xUjtW6w56eAl+OAaFZq2-mRjwThgHRfscS6WLdj1yPE5UBl5RHi86J14WSZoD88Kg2J+Pjom1rh09aXwIbPkF6C87CS3mXaZkV8EyCDB9ApfhSbwD883V9PAU-zyLa+D+TtolLbcx0WrRsTL-DrglwT7ryyFqx1ZrDhVAFg-CMWyE6JKJW3H+tgktfAByeN0oXeApmQ4-I90nzBYVJrEz3OZWPIWNWRyvevgEA6oYsMBAQKKc6hgLr5-ca+beoB6mmq+qaAMDwcRjqVtTOKWLf2k10h7862u0AhEcM0eqHmFpxXdwZVCRmZ4tuH0+IGpMOng966Z00GfymatjIC4-fbxnI1wrYz6pmY5w29PyV+eYCyHVDMF50oNNtROFWVLpTXzVo18vs-707N-5MOapxejQBzP2MdT4s21vGYNNJmEzKZ-tOafkoyHpzeZls51G90JnSzIZnpqAXdOcMvT+ZiAKQs3kHmCGv-BmDiH1Dv7MGjJ6xIKJRyLFHzhsewxYdpZ-KdaWDPAFEZzHY0lSO0+DpAcYC7hvAkZawSdJoLoAbp1NRgFQRgs6lGwVNZwegCQuk1wAHXVC04ONIgBV9XhP2hczrI0wRJJgEoFVVMrEWrKDVQNQ5WsCtDCCq+mYhdsSOTZ4g94GaHsAiWG4miqhJi3YkIv-JxEEQFgcarkGmrn4Gk9eNExkuiWei6MC2kgCtrygHwttXaYRndB9AXaoDGNV4UotzBqqZlDKv7S9aDqGLUgQSzMhYs+kEJIl44OJdkF0DOByIGS+DXkuOXzauVVSzbWGKaWjM2l52t-Vdq0YA0Bl4ytRdMtaVzLgaoOptOwQgWSCYF9ACWGIStR1oLUIAA)
2. Hover just under the text of the partially-hidden tab "NewStatefulLayout.js"

Expected:

It to just show normally as fully hovered, like when you hover over the text itself.

Actual:

A very odd and slightly discomforting blinking of it going between focused with the tab fully expanded, like when you hover over the text itself, and not, like when you're not hovering over the bar at all. (I don't even have issues with most animations.)

**Comment by porsager** [comment]
Ah, it seems like it's because a scrollbar appears which catches the hover, so you have to move the mouse slightly higher and the scrollbar disappears. Is that what you're experiencing?

**Comment by isiahmeadows** [comment]
I don't see a scrollbar at all, but I'm on Mac where scroll bars are typically not displayed unless you're scrolling.

**Comment by porsager** [comment]
I can't replicate this issue (not anymore at least), so I'll close this out.. Feel free to reopen if you still experience it ;)
