### ISSUE TITLE
flems.io/react is outdated

### ISSUE THREAD

**Issue by CreaturesInUnitards** [porsager/flems.io#32]
Should be e.g.

```jsx
const root = ReactDOM.createRoot(app)
root.render('Hello, world!`)
```

**Comment by pygy** [comment]
The old API is still working for now, but there's a deprecation warning.

**Comment by porsager** [comment]
Fixed - :P Little late, but not much love for react so...

**Comment by CreaturesInUnitards** [comment]
🙌🙏

Thanks Rasmus!

(No love for React here either, but the kids at work need all the help they can get 😁)
