### ISSUE TITLE
flems.io/robots.txt and flems.io/sitemap.xml paths could be handled better

### ISSUE THREAD

**Issue by hilja** [porsager/flems.io#33]
These two paths: `/robots.txt` and `/sitemap.xml` are used by search engines to look for the `robots.txt` and sitemaps. The paths should either contain a valid `robots.txt` and valid `sitemap.xml`, or return 404 status code if you don't want to add them.

This doesn't really make flems editor better or worse, but it would play nicer with the outside world.

Also if you throw in a random path `/asdfasdf` (or `/asdfasdf.foo`) it creates the file and returns an error in the console. Could this be captured earlier?

![Screenshot 2023-04-02 at 13 26 09](https://user-images.githubusercontent.com/2558021/229349931-4d36e4ad-aeb5-4ea8-8b9d-42797c8f6dc6.png)

And thanks for making flems.io as great as it is already!

**Comment by porsager** [comment]
those extra paths is a quick way to require modules from unpkg (npm) ;) 

About robots and sitemap files, I think the search engines will do fine without..

Thanks for the kind words.
