### ISSUE TITLE
changing order of tabs

### ISSUE THREAD

**Issue by diomed** [porsager/flems.io#36]
hello

it's quite annoying to see tabs being 

.html  .js  .css

I'm used everywhere for them to be in

.html  .css  .js  

order

Is is possible to make it so that we could slide tabs however we want, or that CSS tab would be 2nd in line?

**Comment by diomed** [comment]
it also starts with code on .js window because why?

it's rarely ever one goes to write JS first, when there's HTML to be filled

**Comment by porsager** [comment]
That's what I do ;) I find it annoying the css or html is even there..

**Comment by porsager** [comment]
Bookmark this link https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0ALeBbKIANCAGYCWMYaA2qAHYCGuEamO+RIsA9nYn6xABfQvSYt0GWGCrEefCAPTCAukKA ;)

**Comment by porsager** [comment]
Or this one if you still want the .js file... https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0ALeBbKIAvkA

About the order of the tabs, I'll consider making that optional, since it's a bit silly they can't be moved around outside type boundaries.

**Comment by diomed** [comment]
> Bookmark this link https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0ALeBbKIANCAGYCWMYaA2qAHYCGuEamO+RIsA9nYn6xABfQvSYt0GWGCrEefCAPTCAukKA ;)

that link has no .js window. i still need js window. but not forced as first one

**Comment by diomed** [comment]
> Or this one if you still want the .js file... https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0ALeBbKIAvkA
> 
> About the order of the tabs, I'll consider making that optional, since it's a bit silly they can't be moved around outside type boundaries.

is it possible to have 

.html .css .js with highlight on HTML being first

**Comment by porsager** [comment]
The order is tied for moving in the interface, but can be done through the state, so this url 😋 https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0ALeBbKIANCAGYCWMYaA2qAHYCGuEamO+RIsA9nYn6xABfQvSYt0GWGCrEefCAPTDRIRs1YYAVrK69+8QUIC6QoA

**Comment by diomed** [comment]
> The order is tied for moving in the interface, but can be done through the state, so this url 😋 https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0ALeBbKIANCAGYCWMYaA2qAHYCGuEamO+RIsA9nYn6xABfQvSYt0GWGCrEefCAPTDRIRs1YYAVrK69+8QUIC6QoA

thank you very much. IMHO this should be set as normal starter state of things.

**Comment by porsager** [comment]
I got that much, but would be silly to change my own project to something else than what I prefer myself 😉

**Comment by diomed** [comment]
> I got that much, but would be silly to change my own project to something else than what I prefer myself 😉

you are right. 😄  thank for help 👍
