### ISSUE TITLE
JSX error

### ISSUE THREAD

**Issue by constantin-angheloiu** [porsager/flems.io#38]
Hei @porsager!

It's been a while, but always a pleasure to salute you!
I used flems ever since. Is the fastest way to make and share chunks of ideas.

Lately it seems something's wrong with it; the playground it's unable to understand  syntax

[here's a flems](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvAHgBMIA3AAgjYF4AOiAwAHUcIB8LAPQdOkkAF8K6bLkQEAVgip0GTYnn1xi3AE61aZ-twBKMDNWIARAPIBZfNXOPGdq2IACjFRAEpBNEtrfF80NhhzIJY4UQw0SQAJGCgoWgpuAHdacyg2AEJZVPTJMOVVEEwcPG84XRp6RmZNZQBdKigINABrBBQ1Zs1fJyMqAFdSvBJiUThEGRk5tFFhgHNvWiwZaedNrDZjx2d8BM4c2lEcBnwdShBiAE9RDRA4HwhREYVBMfidiABaNiHN4LciaZardabbZ7A5HMGQw5nC4YqFYG4wO55R6GF7tT7fPB-cwAoG9JRAA)

Hope you're doing well! 🥳 
Have a great day ahead!

**Comment by danloomer** [comment]
Hey @constantin-angheloiu  👋 

Flems only understands valid JavaScript by default, if you want to write JSX code you can change the file to be parsed by babel, or typescript by clicking the gear next to it in the side bar:
![image](https://github.com/porsager/flems.io/assets/59700952/312a10fd-19af-4a6a-8a2c-1464af34a474)

[Here is the same playground but with the js file in babel mode.](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvAHgBMIA3AAgjYF4AOiAwAHUcIB8LAPQdOkkAF8K6bLkQEAVgip0GTYnn1xi3AE61aZ-twBKMDNWIARAPIBZfNXOPGdq2IACjFRAEpBNEtrfF80NhhzIJY4UQw0SQAJGCgoWgpuAHdacyg2AEJZVPTJMMoaWixRaES8ACMMNpz6uByYZwh6BE0ARkQAZgBOZVUQTBw8bzhdBoNmTWUAXSooCDQAa2HUOfU8XycjKgBXUrwSYlE4RBkZK7RRfYBzb0aZc+dXlg2H9HM58AlODlaKIcAx8Dp6sQAJ6iDQgOA+CCiIwqNQLTT-YgAWjYjXqN3Imnuj2er3eXx+WBBFxJvyuQOZzlZWHBMEheRhhnhK2RqLwGPMWJxmyUQA)

**Comment by constantin-angheloiu** [comment]
Thank you @danloomer!
I was totally forgot about that. 

However in prev versions adding flems.com/**react** was doing that by default.
