### ISSUE TITLE
All flems stop working after a while offline

### ISSUE THREAD

**Issue by porsager** [porsager/flems.io#4]
Moved from https://github.com/porsager/flems/issues/16

**Comment by pygy** [comment]
I haven't tried to use Flems while offline since hitting that bug... Has it been fixed?

**Comment by porsager** [comment]
I've been unable to replicate it myself, and I'm currently changing offline mode from the old html5 offline cache to service workers, so I eagerly closed this one out 😇

**Comment by porsager** [comment]
Will be solved in the persistent version of flems.
